#! /bin/sh

#
# 	 ██
# 	░██              ██████
# 	░██       ██████░██░░░██ ███     ██ ██████████
# 	░██████  ██░░░░ ░██  ░██░░██  █ ░██░░██░░██░░██
# 	░██░░░██░░█████ ░██████  ░██ ███░██ ░██ ░██ ░██
# 	░██  ░██ ░░░░░██░██░░░   ░████░████ ░██ ░██ ░██
# 	░██████  ██████ ░██      ███░ ░░░██ ███ ░██ ░██
# 	░░░░░   ░░░░░░  ░░      ░░░    ░░░ ░░░  ░░  ░░
#
#		Zanark's bspwm config
#

# ===================================================
# I. 	autostart
# II.	workspaces
# III.	global settings
# 	IIIA.	directional focus and swap windows
# 	IIIB.	role based focus on windows
# 	IIIC.	cycle focus
# 	IIID.	alt + Tab functionality
# 	IIIE.	history based focus
# IV.	workspace hotkeys
# V.	preselect area hotkeys
# VI.	resize window
# VII.	move window
# ===================================================

bspc rule -r "*"

# I.	autostart

# kill picom and run in bg
#killall picom
#picom --daemon &

# kill xwallpaper and run in bg
killall xwallpaper
xwallpaper --center ~/wall.png &

# kill all polybars and run 'em in bg
killall polybar
/home/zanark/.config/polybar/launch.sh &

# bspwm swallow
#killall bspswallow
#pidof bspswallow || bspswallow &

# dunst notification-daemon
killall dunst
dunst &

# kill sxhkd and run in bg
killall sxhkd
sxhkd &

# II.	workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

# III.	window settings

# window border
bspc config border_width         4

# window gaps
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config automatic_scheme alternate
bspc config initial_polarity second_child

# IV.	mouse pointer settings

bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

# V.	bpwm border colors

bspc config normal_border_color		"#4a5169"
bspc config active_border_color		"#bd93f9"
bspc config focused_border_color 	"#ff79c6"
bspc config presel_feedback_color	"#83fba1"
bspc config urgent_border_color 	"#ff4d4d"

# VI.	bspwm window padding

bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

###---Rules---###
bspc rule -a ranger state=fullscreen

